const fetchHotelsActionType = {
  FETCH_HOTELS_REQUEST: "FETCH_HOTELS_REQUEST",
  FETCH_HOTELS_SUCCESS: "FETCH_HOTELS_SUCCESS",
  FETCH_HOTELS_FAILURE: "FETCH_HOTELS_FAILURE"
};

const loadCitiesOptionsActionType = {
  LOAD_CITY_OPTIONS_REQUEST: "LOAD_CITY_OPTIONS_REQUEST",
  LOAD_CITY_OPTIONS_SUCCESS: "LOAD_CITY_OPTIONS_SUCCESS",
  LOAD_CITY_OPTIONS_FAILURE: "LOAD_CITY_OPTIONS_FAILURE"
};

const loadCountryOptionsActionType = {
  LOAD_COUNTRY_OPTIONS_REQUEST: "LOAD_COUNTRY_OPTIONS_REQUEST",
  LOAD_COUNTRY_OPTIONS_SUCCESS: "LOAD_COUNTRY_OPTIONS_SUCCESS",
  LOAD_COUNTRY_OPTIONS_FAILURE: "LOAD_COUNTRY_OPTIONS_FAILURE"
};

const loadRoomSizeOptionsActionType = {
  LOAD_ROOM_SIZE_OPTIONS_REQUEST: "LOAD_ROOM_SIZE_OPTIONS_REQUEST",
  LOAD_ROOM_SIZE_OPTIONS_SUCCESS: "LOAD_ROOM_SIZE_OPTIONS_SUCCESS",
  LOAD_ROOM_SIZE_OPTIONS_FAILURE: "LOAD_ROOM_SIZE_OPTIONS_FAILURE"
};

const setActionType = {
  SET_CITY_OPTIONS: "SET_CITY_OPTIONS",
  SET_COUNTRY_OPTIONS: "SET_COUNTRY_OPTIONS",
  SET_CITY: "SET_CITY",
  SET_COUNTRY: "SET_COUNTRY",
  SET_START_DATE: "SET_START_DATE",
  SET_END_DATE: "SET_END_DATE",
  SET_ROOM_SIZE: "SET_ROOM_SIZE",
  SET_PAGE: "SET_PAGE"
};

const resetActionType = {
  RESET_CITY_OPTIONS: "RESET_CITY_OPTIONS",
  RESET_COUNTRY_OPTIONS: "RESET_COUNTRY_OPTIONS",
  RESET_SEARCH_FORM: "RESET_SEARCH_FORM",
  RESET_PAGE: "RESET_PAGE"
};

const hotelSearchActionType = {
  ...fetchHotelsActionType,
  ...loadCitiesOptionsActionType,
  ...loadCountryOptionsActionType,
  ...loadRoomSizeOptionsActionType,
  ...setActionType,
  ...resetActionType
};

export { hotelSearchActionType };
