CREATE TABLE [dbo].[Rooms]
(
	[RoomId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Price] DECIMAL(18, 4) NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[HotelId] INT NOT NULL, 
	[Size] INT NOT NULL,
	CONSTRAINT FK_RoomHotel FOREIGN KEY([HotelId]) REFERENCES Hotels(HotelId),
)
